/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.awt.BorderLayout;
import java.util.List;
import java.util.Map;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI
 */
public class DisplayFunctionDetails extends javax.swing.JPanel {

    /**
     * Creates new form DisplayFunctionDetails
     */
    public DisplayFunctionDetails() {
        initComponents();
    }

    public void displayFunctionDetails(List<Map<String, Object>> functionData) {
        // Check if there's data
        if (functionData == null || functionData.isEmpty()) {
            System.out.println("No data available for tickets.");
            return;
        }

        // Column names for the JTable
        String[] columnNames = {"ID de la funcion", "Titulo", "Duracion", "hora funcion"};

        // Convert the data into a 2D array for JTable
        Object[][] data = new Object[functionData.size()][4];

        for (int i = 0; i < functionData.size(); i++) {
            Map<String, Object> ticket = functionData.get(i);
            data[i][0] = ticket.get("FuncionID");
            data[i][1] = ticket.get("Titulo");
            data[i][2] = ticket.get("Duracion");
            data[i][2] = ticket.get("funcion");
        }

        // Create a table model with the data and column names
        DefaultTableModel model = new DefaultTableModel(data, columnNames);

        // If the JTable and JScrollPane are already initialized, just update the model
        if (tableVer == null || ScrollPaneVer == null) {
            tableVer = new JTable(model);
            ScrollPaneVer = new JScrollPane(tableVer);

            // Add the scrollable table to the panel
            this.add(ScrollPaneVer, BorderLayout.CENTER);
        } else {
            // Update the model if JTable already exists
            tableVer.setModel(model);
        }

        // Ensure that the panel is revalidated and repainted to reflect the new table
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPaneVer = new javax.swing.JScrollPane();
        tableVer = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        tableVer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ScrollPaneVer.setViewportView(tableVer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ScrollPaneVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(ScrollPaneVer, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneVer;
    private javax.swing.JTable tableVer;
    // End of variables declaration//GEN-END:variables
}
