/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.connection.DatabaseOperation;
import com.raven.model.Sala;
import com.raven.model.Ticket;
import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import net.miginfocom.swing.MigLayout;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author MSI
 */
public final class DisplaySeats extends javax.swing.JPanel {

    DatabaseOperation db = new DatabaseOperation();
    Sala sala = new Sala();
    Ticket ticket = new Ticket();
    private List<JButton> buttons = new ArrayList<>(); // List to store the buttons

    /**
     * Creates new form TestPanel
     */
    public DisplaySeats() {
        initComponents();
        seats.setLayout(new MigLayout("wrap 8,insets 10,fill,debug", "[][][][]", "")); // [][][][][][][][]
        //CustomPanel();
    }

    public void displaySeats() {
//TP = new JPanel(new MigLayout("wrap 8,insets 10,fill,debug", "[][][][][][][][]", ""));
        System.out.println("click dentro de la clase");
        // Set layout for the existing TP (do not reinitialize)
        //  TP.setLayout(new MigLayout("wrap 8, insets 10, fill,debug", "[][][][]", ""));
        seats.removeAll();

        int funcionID = Integer.parseInt(inputID.getText());

        int capacity = sala.getSalaCapacity(funcionID);

        ArrayList<Integer> bookedSeats = ticket.getBookedSeats(funcionID);
        // Clear the list of buttons (in case of reinitialization)
        buttons.clear();

        // Create and add buttons based on capacity
        for (int i = 1; i <= capacity; i++) {
            JButton button = new JButton(); // Create a new button

            button.setFont(new Font("Arial", Font.BOLD, 12)); // Font family "Arial", bold, size 12

            if (bookedSeats.contains(i)) {
                button.setText("Ocupado"); // Mark booked seat with 'X'
                button.setBackground(Color.RED);
            } else {
                button.setText(String.valueOf("Asiento " + i)); // Show the seat number
                button.setBackground(Color.GREEN); // Set background color to green for available seats

            }
            buttons.add(button); // Store the button in the list
            seats.add(button); // Add the button to the panel
        }
        seats.repaint();
        seats.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seats = new javax.swing.JPanel();
        selectSeat = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        inputID = new javax.swing.JTextField();
        pickSeat = new javax.swing.JButton();
        seatNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seats.setBackground(new java.awt.Color(51, 255, 51));
        seats.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 880, 310));

        selectSeat.setBackground(new java.awt.Color(255, 255, 255));
        selectSeat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVer.setText("Ver/Mostar asientos");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        selectSeat.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 152, -1));

        inputID.setText("1");
        selectSeat.add(inputID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 48, -1));

        pickSeat.setText("Seleccionar Asiento");
        pickSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickSeatActionPerformed(evt);
            }
        });
        selectSeat.add(pickSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 150, -1));
        selectSeat.add(seatNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 60, -1));

        jLabel1.setText("Asiento requerido");
        selectSeat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 94, -1));

        jLabel2.setText("ID de la funcion");
        selectSeat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 93, -1));

        add(selectSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 860, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        displaySeats();
    }//GEN-LAST:event_btnVerActionPerformed

    private void pickSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickSeatActionPerformed
        // TODO add your handling code here:
        ticket.pickSeat(1, Integer.parseInt(inputID.getText()), Integer.parseInt(seatNumber.getText()));
        displaySeats();
    }//GEN-LAST:event_pickSeatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JTextField inputID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pickSeat;
    private javax.swing.JTextField seatNumber;
    private javax.swing.JPanel seats;
    private javax.swing.JPanel selectSeat;
    // End of variables declaration//GEN-END:variables
}
