/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.connection.DatabaseOperation;
import com.raven.model.Funcion;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 *
 * @author MSI
 */
public class GetTicket extends javax.swing.JPanel {

    private final Funcion funcion;
    private DatabaseOperation db;

    /**
     * Creates new form Form_6
     */
    public GetTicket() {
        initComponents();
        funcion = new Funcion();
        db = new DatabaseOperation();
        loadFuncionesData(funcion, displayFunctions1);
    }

    private void loadFuncionesData(Funcion f, DisplayFunctions df) {
        if (f == null) {
            System.out.println("funcion is null!");
        } else {
            List<Map<String, Object>> funcionesData = f.showFunciones();

            // Debug: Print the data to see what we're getting
            if (funcionesData == null || funcionesData.isEmpty()) {
                System.out.println("No data found!");
            } else {
                System.out.println("Data loaded successfully.");
                // Print some sample data
                for (Map<String, Object> funcion : funcionesData) {
                    System.out.println(funcion);
                }
            }

            if (df == null) {
                System.out.println("form5 is null!");
            } else {
                df.displayFunciones(funcionesData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayFunctions1 = new com.raven.form.DisplayFunctions();
        displaySeats1 = new com.raven.form.DisplaySeats();

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(displaySeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(displayFunctions1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displaySeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayFunctions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.form.DisplayFunctions displayFunctions1;
    private com.raven.form.DisplaySeats displaySeats1;
    // End of variables declaration//GEN-END:variables
}
