/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.model.Funcion;
import com.raven.model.Ticket;
import java.util.List;
import java.util.Map;

/**
 *
 * @author MSI
 */
public class GetTicketDetails extends javax.swing.JPanel {

    Ticket ticket;
    Funcion funcion;

    /**
     * Creates new form GetTicketDetails
     */
    public GetTicketDetails() {
        initComponents();
        ticket = new Ticket();
        funcion = new Funcion();
        loadTicketsData(ticket, displayTickets);
        loadFunctionDetails(funcion, displayFunctionDetails);
    }

    private void loadTicketsData(Ticket t, DisplayTickets dt) {
        // Get the data from the Salas class
        //List<Map<String, Object>> peliculasData = pelicula.showMovies();

        if (t == null) {
            System.out.println("ticket is null!");
        } else {
            List<Map<String, Object>> ticketsData = t.showAllTicketsByUser(1);

            // Debug: Print the data to see what we're getting
            if (ticketsData == null || ticketsData.isEmpty()) {
                System.out.println("No data found!");
            } else {
                System.out.println("Datos cargados con exito.");
                // Print some sample data
                for (Map<String, Object> ticketData : ticketsData) {
                    System.out.println(ticketData);
                }
            }

            // Display the data in the SalasPanel (Form_2)
            //home2.displayMovies(peliculasData);
            if (dt == null) {
                System.out.println("form5 is null!");
            } else {
                dt.displayTickets(ticketsData);
            }
        }
    }

    private void loadFunctionDetails(Funcion f, DisplayFunctionDetails dft) {
        // Get the data from the Salas class
        //List<Map<String, Object>> peliculasData = pelicula.showMovies();

        if (f == null) {
            System.out.println("ticket is null!");
        } else {
            List<Map<String, Object>> functionsData = f.showFuncionDetails(1);

            // Debug: Print the data to see what we're getting
            if (functionsData == null || functionsData.isEmpty()) {
                System.out.println("No data found!");
            } else {
                System.out.println("Datos cargados con exito.");
                // Print some sample data
                for (Map<String, Object> functionData : functionsData) {
                    System.out.println(functionData);
                }
            }

            // Display the data in the SalasPanel (Form_2)
            //home2.displayMovies(peliculasData);
            if (dft == null) {
                System.out.println("form5 is null!");
            } else {
                dft.displayFunctionDetails(functionsData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayTickets = new com.raven.form.DisplayTickets();
        displayFunctionDetails = new com.raven.form.DisplayFunctionDetails();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(displayTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(displayFunctionDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(displayFunctionDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.form.DisplayFunctionDetails displayFunctionDetails;
    private com.raven.form.DisplayTickets displayTickets;
    // End of variables declaration//GEN-END:variables
}
