/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

import com.raven.connection.DatabaseOperation;
import com.raven.model.ModelUser;
import com.raven.model.Usuario;
import java.util.List;
import java.util.Map;
import javax.swing.Icon;

/**
 *
 * @author yael
 */
public class Perfil extends javax.swing.JPanel {

    static DatabaseOperation db;
    static Usuario usuario;

    ModelUser user;
    Icon profile;

    /**
     * Creates new form Actualizar
     *
     * @param user
     */
    public Perfil(ModelUser user) {

        this.user = user;

        usuario = new Usuario();

        db = new DatabaseOperation();
        initComponents();

        if (user.getProfile() != null) {
            pic.setIcon(user.getProfile());
        } else {
            profile = new ImageIcon(getClass().getResource("/com/raven/icon/user_1.png"));
            pic.setIcon(profile);
        }

        List<Map<String, Object>> userData = usuario.getUserData(user.getUserID());
        for (Map<String, Object> data : userData) {
            System.out.println(data);

            //pic.setIcon(user.getProfile());
            txtNombre.setText(user.getName());
            //txtNombre.setText(data.get("UserName").toString());
            txtCorreo.setText(data.get("Email").toString());
            txtContraseña.setText(data.get("Password").toString());
            txtRol.setText(data.get("rol").toString());

//            if (data.get("Profile") != null) {
//                profile = new ImageIcon((byte[]) data.get("Profile"));
//            } else {
//                profile = new ImageIcon(getClass().getResource("/com/raven/icon/user_1.png"));
//                pic.setIcon(profile);
//            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        perfilTitle = new javax.swing.JLabel();
        lblSeparador = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();
        pic = new com.raven.swing.ImageAvatar();
        editButton1 = new com.raven.swing.EditButton();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perfilTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        perfilTitle.setText("Mi Perfil");
        jPanel4.add(perfilTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        lblSeparador.setForeground(new java.awt.Color(204, 0, 51));
        lblSeparador.setText("**************************************************************************");
        jPanel4.add(lblSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 480, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Enter");
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        lblNombre.setText("Nombre");
        jPanel4.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        lblCorreo.setText("Correo");
        jPanel4.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        lblContraseña.setText("Contraseña");
        jPanel4.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        lblRol.setText("Rol");
        jPanel4.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 190, -1));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel4.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 190, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel4.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 190, -1));

        txtRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRolActionPerformed(evt);
            }
        });
        jPanel4.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 190, -1));

        editButton1.setBackground(new java.awt.Color(51, 0, 51));
        editButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/search.png"))); // NOI18N
        editButton1.setText("editButton1");
        editButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton1ActionPerformed(evt);
            }
        });
        pic.add(editButton1);
        editButton1.setBounds(70, 100, 30, 31);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRolActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        //txtNombre.setText(user.getName()+"fgggsdgdf");
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void editButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton1ActionPerformed
        // TODO add your handling code here:
        new Usuario().updateProfilePicture(user.getUserID(), pic);
//        JFileChooser ch = new JFileChooser();
//        ch.setFileFilter(new FileFilter() {
//            @Override
//            public boolean accept(File file) {
//                String name = file.getName().toLowerCase();
//                return file.isDirectory() || name.endsWith(".png") || name.endsWith(".jpg");
//            }
//
//            @Override
//            public String getDescription() {
//                return "Image File";
//            }
//        });
//        int option = ch.showOpenDialog(this);
//        if (option == JFileChooser.APPROVE_OPTION) {
//            File file = ch.getSelectedFile();
//            ImageIcon icon = new ImageIcon(file.getAbsolutePath());
//            pic.setIcon(icon);
//            repaint();
//            try {
//                String sql = "update `user` set `Profile`=? where UserID=? limit 1";
//                Connection conn = db.connectToDatabase();
//                PreparedStatement p = conn.prepareStatement(sql);
//                p.setBinaryStream(1, Files.newInputStream(file.toPath()));
//                p.setInt(2, user.getUserID());
//                p.execute();
//            } catch (IOException | SQLException e) {
//                System.err.println(e);
//            }
//        }
    }//GEN-LAST:event_editButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.EditButton editButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblSeparador;
    private javax.swing.JLabel perfilTitle;
    private com.raven.swing.ImageAvatar pic;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRol;
    // End of variables declaration//GEN-END:variables
}
