/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.main;

import com.raven.event.EventMenuSelected;
import com.raven.form.Perfil;
import com.raven.form.AddRooms;
import com.raven.form.AddMovies;
import com.raven.form.CancelTicket;
import com.raven.form.DisplayFunctions;
import com.raven.form.DisplayMovies;
import com.raven.form.GetTicket;
import com.raven.form.GetTicketDetails;
import com.raven.model.Funcion;
import com.raven.model.ModelUser;
import com.raven.model.Ticket;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;

/**
 *
 * @author MSI
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form EntryPoint
     */
    private DisplayMovies displayMovies;
    private AddRooms addRooms;
    private AddMovies addMovies;
    private DisplayFunctions displayFunctions;
    private Funcion funcion;
    private GetTicket ticketNuevo;
    private Ticket ticket;
    private GetTicketDetails ticketsDetails;
    private ModelUser ctmer;
    private CancelTicket cancelarTicket;
    private Perfil perfil;

    public Customer(ModelUser ctmer) {
        initComponents();
        //setBackground(new Color(0, 0, 0, 0));
        //admin = new Usuario();
        this.ctmer = ctmer;
        displayMovies = new DisplayMovies();
        addRooms = new AddRooms();
        addMovies = new AddMovies();
        displayFunctions = new DisplayFunctions();
        funcion = new Funcion();
        ticketNuevo = new GetTicket();
        ticket = new Ticket();
        ticketsDetails = new GetTicketDetails();
        cancelarTicket = new CancelTicket();
        perfil = new Perfil(ctmer);

        menu.initMoving(Customer.this);
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    setForm(perfil);
                } else if (index == 1) {
                    setForm(displayFunctions);
                    loadFuncionesData(funcion, displayFunctions);
                } else if (index == 2) {
                    setForm(ticketNuevo);
                    System.out.println("tickettt");
                } else if (index == 3) {
                    setForm(ticketsDetails);
                    //loadTicketsData();
                } else if (index == 4) {
                    setForm(cancelarTicket);
                    System.out.println("shsdh");
                } else if (index == 12) {
                    System.out.println("shffffffffffffffff");
                    Customer.this.dispose();
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            new Main().setVisible(true);  // Open Main frame
                        }
                    });
                }
            }

        });
        //  set when system open start with home form
        //setForm(new DisplayMovies());
        setForm(perfil);
    }

    private void setForm(JComponent com) {
        panelPrincipal.removeAll();
        panelPrincipal.add(com);
        panelPrincipal.repaint();
        panelPrincipal.revalidate();
    }

    private void loadFuncionesData(Funcion f, DisplayFunctions df) {
        if (f == null) {
            System.out.println("funcion is null!");
        } else {
            List<Map<String, Object>> funcionesData = f.showFunciones();

            // Debug: Print the data to see what we're getting
            if (funcionesData == null || funcionesData.isEmpty()) {
                System.out.println("No data found!");
            } else {
                System.out.println("Datos cargados con exito.");
                // Print some sample data
                for (Map<String, Object> funcion : funcionesData) {
                    System.out.println(funcion);
                }
            }

            if (df == null) {
                System.out.println("form5 is null!");
            } else {
                df.displayFunciones(funcionesData);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder = new com.raven.swing.PanelBorder();
        panelPrincipal = new javax.swing.JPanel();
        menu = new com.raven.component.MenuCustomer();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorderLayout = new javax.swing.GroupLayout(panelBorder);
        panelBorder.setLayout(panelBorderLayout);
        panelBorderLayout.setHorizontalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE))
        );
        panelBorderLayout.setVerticalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param user
     * @param args the command line arguments
     */
    //public static void main(Usuario user) {
    public static void main(ModelUser user) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer(user).setVisible(true);
            }
        });
    }

    public static void main(String[] x) {
        ModelUser user = new ModelUser("user", 2, "correo", "Customer", null);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.MenuCustomer menu;
    private com.raven.swing.PanelBorder panelBorder;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
